### PR TITLE
fixup! Fix column sizes of types for JDBC driver

### PR DESCRIPTION
**Pull request by maciejgrzybek**
This fixes product tests left behind by that commit.

### CODE REVIEW

**Comment by cawallin** [comment]
looks good!

**Comment by maciejgrzybek** [comment]
Added one more product tests fixup: 8027c70
CC @ebd2

**Comment by electrum** [comment]
How do I run the product tests for just this commit?

Might need more fixes for 535f6bef3f0a4f351cefbf39ec07589ade4daf05

**Comment by maciejgrzybek** [comment]
@electrum checkout commit and use `presto-product-tests/bin/run_on_docker.sh`, possibly specifying a subset of groups (e.g. using `-g group_name`) to shorten execution time.
Thanks for point out 535f6be, will have a look once I solve a problem with classes clash on different class loaders problem.

**Comment by electrum** [comment]
Please title the commits:
- Fix product tests for JDBC column sizes
- Fix product tests for complex use of window functions

**Comment by maciejgrzybek** [comment]
Started PR against prestodb/presto.

**Pull request closed without merging**
