### PR TITLE
Fix build checks

### PR DESCRIPTION
**Pull request by akshatnair**
Import order and unused import error fixed that was introduced
by commits 92fbb4d and 35f290d.

### CODE REVIEW

**Comment by ArturGajowy** [comment]
I'd say let's not wait for a review if the sprint branch is red and the fix is trivial.

**Comment by cawallin** [comment]
sorry, and thanks for fixing it :( I ran it on dupa and it seemed fine, guess I changed something last minute.

**Comment by ArturGajowy** [comment]
NP :) Guys, did you ask @arhimondr what 'dupa' means? What did he tell you? :D

**Comment by akshatnair** [comment]
@ArturGajowy I already know what it means :P hahaha

**Comment by arhimondr** [comment]
Distributed Unbelievably Performant Automation

**Pull request merged**
