### PR TITLE
Allow debugging MySQL and PostgreSQL connectors

### PR DESCRIPTION
**Pull request by sanjay990**

### CODE REVIEW

**Comment by sanjay990** [comment]
@maciejgrzybek @brian-rickman

**Comment by brian-rickman** [comment]
Looks OK to me, though a more descriptive commit message would be nice.

**Comment by sanjay990** [comment]
Updated commit message

**Comment by brian-rickman** [comment]
LGTM

**Comment by maciejgrzybek** [comment]
Rename commit's summary to: `Add properties files for MySQL and Postgres in tests`
In further lines you can explain why it's needed.
Currently, your commit msg is not true. You're not enabling debugging of connectors in product tests. You just make it possible by default (with no effort of configuring anything).

Otherwise, LGTM.

**Pull request merged**
