### PR TITLE
Rpm updates

### PR DESCRIPTION
**Pull request by cawallin**
I'm working on the presto-admin automated test for this (checking that the server is started with the presto user).

### CODE REVIEW

**Comment by cawallin** [comment]
@jreslock @rschlussel @mattsfuller @anusudarsan

**Comment by rschlussel-zz** [comment]
Did you test that using Presto works too (creating tables, etc.)?

**Comment by cawallin** [comment]
It works with querying, CTAS, INSERT INTO, DROP TABLE

**Comment by rschlussel-zz** [comment]
k.  Looks good.

**Comment by anusudarsan** [comment]
lgtm

**Pull request merged**
