### PR TITLE
Add GRANT query support for hive connector: revised

### PR DESCRIPTION
**Pull request by amrutagokhale**
Opening a new PR for the revised code. @petroav can you take a quick look?

Here is the syntax that this commit adds suport for:
GRANT privilege ((, privilege)\* | ALL PRIVILEGES)
        ON (TABLE)? tablename TO (username | PUBLIC)
        (WITH GRANT OPTION)?

The syntax differs in some respect from sql-1999 standard. 
For ex., the current syntax doesn't support specifying multiple 
grantees. We will eventually make it compliant with the standards.

Module-wise code changes:
- Parser: add the GRANT syntax
- SPI: define the default grant behavior as well as check for grant
- Security: add access control check for grant
- Hive: add access control checks for the three security modes

I have added the Enum class 'Privilege' under SPI. This represents the
privilege(s) that you can specify using the GRANT statement. Addition
of this class to SPI is necessary so that functions in SPI can refer
to 'Privilege' enum type. A similar addition to Parser module wouldn't
have sufficed, since functions in SPI can't refer to classes defined
in parser module (that would result in a circular dependency).

### CODE REVIEW

**Comment by amrutagokhale** [comment]
I have changed the condition on which the granting of a privilege succeeds. Now, granting a privilege of type T succeeds if the grantor holds both, the GRANT privilege and the specified privilege T. The reasoning behind this is:

There is a "WITH GRANT OPTION" in the grant statement. To the best of my interpretation, this gives the power to grant that specific privilege to the grantee. For ex., if a user "bob" issues -- "grant select on customers to alice with grant option", then this gives alice the right to only grant the select privilege, and not the right to grant, say insert, privilege. By checking that a user possesses both, the mentioned privilege and the GRANT privilege, we ensure that this is the case (This might raise the question of what will happen if a user revokes his/her privilege. Should this user be able to still grant the revoked privilege to someone else? Per my implementation, this won't be allowed).

I also referred to the sql-standard document, looking for answers on the intended behavior. The standards document doesn't exactly specify when grant should succeed, but this is what my interpretation is.

@cawallin @rschlussel Correct me, if I am wrong.

**Comment by cawallin** [comment]
That's accurate, as far as I know. If a privilege is revoked, I'd say that you can't grant, but that seems like something a flag you can check for in the database and would be database-specifi

**Comment by petroav** [comment]
I think your edit that only principals who hold both the privilege and GRANT are able to grant that privilege is correct. Did you get a chance to experiment to see if Postgres does it like this? Regardless, I think it's a security vulnerability to allow principals to grant privileges they themselves don't hold. That way if `anton` were granted SELECT, I could then as myself grant to `anton` all remaining privileges.

I think we're ready to do a PR against FB.

**Comment by amrutagokhale** [comment]
@petroav Yeah, that's a good point!

**Comment by amrutagokhale** [comment]
In light of what @rschlussel said, I have changed the condition on which grant will succeed. For hive connector, grant succeeds if either one of the following is true:
- check whether user is owner of the table
- check whether user has the mentioned privilege on the table with grantOption flag set to true

In Hive, the owner of the table does not have the grantOption flag set to true in the metadata record for the corresponding privilege. So it is essential to check whether user is the owner as a separate condition. As for the case when owner revokes his/her granting privilege, this case won't arise. AFAIK, one can't revoke their ownership of a table, and hence can't revoke the granting privilege they automatically get because of being the owner. 

The grantOption flag might be implemented differently in different databases, so the implementation will change accordingly.

**Comment by amrutagokhale** [comment]
Closing this ticket since the code was merged.

**Pull request closed without merging**
