### PR TITLE
Fix kerberos ticket refreshing algorithm

### PR DESCRIPTION
**Pull request by losipiuk**
@arhimondr 
please take a look

### CODE REVIEW

**Comment by arhimondr** [comment]
lgtm

**Comment by mouendless** [comment]
Could anybody make a patch for this commit? cuz the 141.1t does not patch this and kerberos on cluster always fails after a period.

**Comment by mattsfuller** [comment]
Hi @mouendless what version are you using? We haven't spun a 141.1t release yet. The latest code on our branch release/141t should have this fix. https://github.com/Teradata/presto/commits/release/141t.

We plan to cut a maintenance release for 141t soon.

**Comment by mouendless** [comment]
Hi @mattsfuller I download from the website and meet the kerberos out of date problem, then I check the release here https://github.com/Teradata/presto/releases/tag/141.1t and saw this fix not in there.

**Comment by mattsfuller** [comment]
@mouendless sorry I was incorrect. What I meant was we have not spun a maintenance release to include the kerberos out of data problem yet. We do plan to release on soon. Will likely be named 141.2t.

**Comment by mouendless** [comment]
@mattsfuller that's ok and I'm looking forward to it. Thx.

**Pull request merged**
