### PR TITLE
Add documentation for custom hive storage handler

### PR DESCRIPTION
**Pull request by rschlussel-zz**
Document how to query tables that require custom storage handlers.

Testing: build docs

### CODE REVIEW

**Comment by rschlussel-zz** [comment]
@KBP-TDC

**Comment by kbajda** [comment]
@rschlussel : any chance we can tell that presto-admin can help with jar distribution?

**Comment by rschlussel-zz** [comment]
I can definitely add that.  In the last release there was a script to link between presto-admin and presto docs.  Are we doing that again?

**Comment by cawallin** [comment]
@rschlussel I'm assuming so; our goal with the documentation is the same (make customers use presto-admin -- though we'll have to go through our script to cut out less of the presto docs)

**Comment by rschlussel-zz** [comment]
I updated the documentation to include presto-admin commands and the need to restart, and we'll add links later.

**Comment by cawallin** [comment]
Looks good

**Pull request closed without merging**
