### PR TITLE
Add test for TPC-DS connector

### PR DESCRIPTION
**Pull request by rschlussel-zz**
Wrote one test for the TPC-DS connector.  Let me know if there are other tests that you think I should write.  @petroav

### CODE REVIEW

**Review by petroav — APPROVED** [review]
Looks good. TPC-H is implicitly tested via `AbstractTestQueries` so maybe with time as we add more tests maybe we can start using TPC-DS tables.

You could add a couple more queries that exercise all tables. That would be a good way of testing the interaction of the generator with the connector. Although I don't think we special case for tables. I don't feel too strongly about this so feel free to leave it as is and if Dain asks for more tests we can add them.

**Comment by rschlussel-zz** [comment]
If we added tpcds tests to abstract test queries, they will fail with the TpchQueryRunner.  We'd need to separate them better and define which connectors can run which tests

**Comment by petroav** [comment]
Not if we loaded them in H2; but I see your point.

**Comment by rschlussel-zz** [comment]
No because you can't add tables to the tpch connector.  The other connectors get data loaded, so it's fine.  But the tpch connector can't.

**Comment by rschlussel-zz** [comment]
merged to the tpcds-connector branch

**Pull request closed without merging**
