### PR TITLE
Fix error message when view creation fails because of lack of grant privilege

### PR DESCRIPTION
**Pull request by amrutagokhale**
Fixes https://github.com/prestodb/presto/issues/5632.

Testing: manual.

### CODE REVIEW

**Comment by rschlussel-zz** [comment]
looks good.  Can you add a  test?

**Comment by amrutagokhale** [comment]
If you mean adding a product test, I am going to add one as part of adding product tests for all access control checks in another PR.

**Comment by rschlussel-zz** [comment]
ok.  make a note of that when you open a PR against prestodb.

**Comment by amrutagokhale** [comment]
Will do, thanks.

**Comment by amrutagokhale** [comment]
PR against prestodb: https://github.com/prestodb/presto/pull/5648.

**Pull request closed without merging**
