### PR TITLE
Add LDAP authentication tests for Simba JDBC driver

### PR DESCRIPTION
**Pull request by brian-rickman**
This is a port of the tests in PrestoLdapCliTests.

Only the last two commits (9eeba7e, e4af7c7) are relevant to this review.  The others are required to make it possible to run the tests on Sprint-38.

### CODE REVIEW

**Comment by sopel39** [comment]
I have commented https://github.com/Teradata/presto/commit/9eeba7e72715793aa41a1de88a84559ed034b83b (comments in the commit). I don't knot though why `prestoSslPort` is null. Maybe wrong config file is read?

**Comment by brian-rickman** [comment]
@sopel39 I am sure the correct config file is being read as changes to other properties do take effect.

Thanks for the review.  I'll keep playing with the config file.

**Comment by sanjay990** [comment]
yes, -g and -x are not supported. So we can have the following groups.
1. ldap_cli - Run CLI ldap tests
2. ldap_jdbc  - Run simba jdbc ldap tests
3. ldap - Run all the ldap related tests.

**Comment by ArturGajowy** [comment]
@sanjay990 I asked @kokosing a few days ago and he said it is supported now. Haven't checked yet, though. Can you confirm that experimentally? :)

**Comment by anusudarsan** [comment]
https://github.com/prestodb/tempto/issues/117 - this is the tempto issue. Not sure what version of tempto fixed it. We are still on 1.12 on the sprint branch.

**Comment by anusudarsan** [comment]
There is an outstanding FB PR from @kokosing to update tempto to 1.14, which we should probably add to our sprint branch.

**Comment by brian-rickman** [comment]
@sopel39 I found out why prestoSslPort is always null.  It is because the value is all digits.  If I replace `8443` with `test` then the string `test` is assigned to the variable.

Enclosing the number in quotation marks appears to solve the problem, though I find this to be unintuitive.  

The alternative is to parse the value of cli_ldap_server_address, which looks like `https://host:port`.  I'm thinking that may be the better answer as it shares an existing config property with the CLI tests instead of adding a new one.

**Comment by sopel39** [comment]
Maybe if `prestoSslPort` was Integer it would work too. Anyway, error should be thrown instead of setting null. I will file a issue referencing this PR

**Comment by brian-rickman** [comment]
I addressed all the review comments in the final version of the test and merged it to Anu's ldap-tests branch with this commit: 162268a63a528399c3ed17cc1c7082103f3975d4 .

**Pull request closed without merging**
