### PR TITLE
fix decimal statis rescale in presto-orc tuple domain predicate

### PR DESCRIPTION
**Pull request by sopel39**
@KBP-TDC

### CODE REVIEW

**Comment by arhimondr** [comment]
lgtm

**Comment by cawallin** [comment]
Can you add a test that would catch this issue in the future?

**Comment by sopel39** [comment]
Yes, there are tests cases in TestTupleDomainOrcPredicate.java

**Comment by cawallin** [comment]
I saw those, but some more end-to-end test would be good as well; the TestTupleDomainOrcPredicate tests all seem kind of isolated from real life.

**Comment by kbajda** [comment]
@sopel39 : is that something that can be reliably tested without product tests?
Should we add more boundary testing for ALL sql datatypes?

**Comment by sopel39** [comment]
The cases I have added test exactly the issue there was in presto-orc. It is rather simple really. The only thing that could be tested more is if ORC would store decimal stats with greater scale than that of the column. Although I think it is unlikely, this is something that could be verified in ORC spec. I don't think it is required to add such product tests because they would rather test ORC spec and not Presto.

**Comment by sopel39** [comment]
For other sql types I can double check if there are some potential problems

**Pull request closed without merging**
