### PR TITLE
Small refactoring patches.

### PR DESCRIPTION
**Pull request by fiedukow**

### CODE REVIEW

**Comment by kokosing** [comment]
Nice work! I like the way you separated commits and that you updated release notes. Hope it will get into 0.140, otherwise you need to rebase it to some other version.

lgtm % comments

**Comment by kokosing** [comment]
I wonder why airlift duration is better than java's one. Maybe you could some Durations class with a static method plus or add such method to airlift's duration (https://github.com/airlift/airlift).

**Comment by kokosing** [comment]
I think you have used `git push -f`, all the comments gone.

**Comment by fiedukow** [comment]
I thought that's a workflow we use. I wasn't happy about losing comment too, but I think I've addressed all of them ;)

As for the airlift duration, I think it's used because of the fact that it comes from REST API and no one wants to convert one Duration to another. I add this and PR to airlift but I think I should not wait for that with this patch ;-)

**Comment by fiedukow** [comment]
moved to fb repo https://github.com/facebook/presto/pull/4693

**Pull request closed without merging**
