### PR TITLE
Introduce required implicit coercions and casts for DECIMAL type

### PR DESCRIPTION
**Pull request by arhimondr**
Brief list of introduced changes:
- Refactor signature match and bind algorithm
- Allow `BIGINT` to `DECIMAL` and `DECIMAL` to `DOUBLE` implicit coercions
- Resolve ambigulities in function invokations 
- Implement `DECIMAL` to `JSON` and `JSON` to `DECIMAL` cast operators

### CODE REVIEW

**Comment by sopel39** [comment]
Can one of the admins verify this patch?

**Comment by rschlussel-zz** [comment]
Could the commit at https://github.com/Teradata/presto/tree/unknown_functions get squashed in to https://github.com/Teradata/presto/commit/9346c9d8ed58106e214ba6f5022595716462b5d0 (Resolve ambiguities for the operator invocations with unknown type)?
It's separate on the integration branch since decimal_coercions was already merged in, but ultimately it's a fixup commit.

**Comment by arhimondr** [comment]
@rschlussel will do

**Comment by rschlussel-zz** [comment]
thanks

**Pull request closed without merging**
