### PR TITLE
Decimal 3

### PR DESCRIPTION
**Pull request by pnowojski**
Supersedes https://github.com/Teradata/presto/pull/89

### CODE REVIEW

**Comment by losipiuk** [comment]
Updated with bunch of fixes

**Comment by pnowojski** [comment]
I have pushed changes that @losipiuk mentioned aboved

**Comment by martint** [comment]
I'm about to start reviewing this. Can you create a PR on the presto repo?

**Comment by losipiuk** [comment]
If I understand githubs PR model correctly, it cannot be moved to facebook/presto as this PR is based on Teradata:parametric_varchar_v4.

If we just base this on master all the commits which are present in Teradata:parametric_varchar_v4 (which corresponds to https://github.com/facebook/presto/pull/4316 PR) would also be visible here.

Is that your intention?

**Comment by martint** [comment]
Yes, that's ok. I can just ignore the commits related to the varchar feature. Once that's merged, we can rebase the decimal PR on top of master and those commits will disappear.

**Comment by losipiuk** [comment]
superseded by https://github.com/facebook/presto/pull/4426

**Pull request closed without merging**
