### PR TITLE
Updating sprint-29 version to 144t.

### PR DESCRIPTION
**Pull request by fiedukow**
@cawallin

### CODE REVIEW

**Comment by cawallin** [comment]
The version should be 144t-SNAPSHOT, since the branch is still changing. We can change it to 144t at the end of the sprint if we want to.

**Comment by fiedukow** [comment]
That was my previous attempt but as it turns out it's impossible to use such version as path to certain artifacts is one character to long then.
No, I'm not kidding. This seems to be a well known fact that this is the case.

**Comment by cawallin** [comment]
There is a fix for it in the integration branch. let me find it for you.

**Comment by cawallin** [comment]
https://github.com/Teradata/presto/commit/a3a0c9e084fe873ce9ef39228d86cb211e2d258b

**Comment by fiedukow** [comment]
Thanks, I was aware of that "solution", but I wouldn't call this a fix rather a workaround.

Anyway good to know that we already had that patch ready, I've included it to this PR and change version back to 0.144t-SNAPSHOT :-)

**Comment by cawallin** [comment]
yes, it is a workaround, but if we don't have SNAPSHOT Maven would be confused :)

looks good, thanks!

**Comment by fiedukow** [comment]
merged

**Pull request closed without merging**
