### PR TITLE
Remove s3_tests from quarantine

### PR DESCRIPTION
**Pull request by rschlussel-zz**
Instead only run the tests if the tables exist, and warn if they do not
exist.

My concern with this is that we won't notice if the tests stop working since they'll pass anyway.  
@brian-rickman

### CODE REVIEW

**Comment by brian-rickman** [comment]
I am concerned that this test will run and pass without generating a warning if it is run after an unrelated test creates those tables.  If we can't verify that the tables are on S3 rather than HDFS, can you rename them to make their intended location clear, i.e. nation_s3, alltypes_s3_[format].

**Comment by rschlussel-zz** [comment]
@brian-rickman addressed comment

**Comment by brian-rickman** [comment]
LGTM.  Thanks.

**Comment by rschlussel-zz** [comment]
merged

**Pull request closed without merging**
