### PR TITLE
cache the m2 directory

### PR DESCRIPTION
**Pull request by joshk**
Sorry, this PR description is a little blank.

This is a test to see if caching will speed up the build.

### CODE REVIEW

**Comment by ArturGajowy** [comment]
Have a look at [this](https://github.com/ArturGajowy/presto/commit/0e894ed8c5314ddd2ce037dddfd182f89ec8ae79#diff-354f30a63fb0907d4ad57269548329e3R27) - you'll likely need at least one line from there :)

**Comment by ArturGajowy** [comment]
Also, we need to remove all jars built by our builds before archiving the cache. Otherwise our caches will get polluted (and will needlessly weigh at 500 more thanks to presto-server-rpm itself)

**Comment by ArturGajowy** [comment]
Oh, it's you Josh :D I thought it's s/b new at Teradata :) I think I'll give caching another try next week :)

**Comment by joshk** [comment]
@ArturGajowy what jars need to be removed? There is a `before_cache` section we can use for this.

**Comment by joshk** [comment]
I want to help you and your team take full use of Travis, happy to help where I can. I see the Premium VMs helped a little, but I think there is more we can do :)

**Comment by ArturGajowy** [comment]
I think it'll be enough to remove `.m2/repository/com/facebook`

**Comment by ArturGajowy** [comment]
Sure thing! Thanks for your help! :)

**Comment by joshk** [comment]
I can confirm that the cache is 1.5gigs with everything. I'll try adding that line and see how much that helps :)

**Comment by joshk** [comment]
Also, @ArturGajowy, I had an idea, are you running tests against a Presto instance? or something that uses a lot of IO?

**Comment by ArturGajowy** [comment]
Yeah, we run presto + hive in docker containers. What's the idea? :)

**Comment by joshk** [comment]
Ahhhhhh, I have a great idea, I saw it made a customers builds 1/3 faster when Docker was told to use a tmpfs. Can you spare the ram? Maybe a gig or two?

**Comment by joshk** [comment]
Removing those files from the cache removed 1.2Gigs from the cache 👍

**Comment by ArturGajowy** [comment]
The product tests (run on docker) were, I think, at the limits of memory usage. But since we have twice as much RAM now, why not try? Worst thing that can happen, we'll enable that tweak only on workers having enough RAM :)

**Comment by joshk** [comment]
I'll see what I can whip up 😄

**Pull request closed without merging**
