### PR TITLE
Update expected results for TPC-DS query 36 and 86

### PR DESCRIPTION
**Pull request by petroav**
Update the expected data type from LONGNVARCHAR to CHAR
and pad the expected results accordingly.

### CODE REVIEW

**Comment by petroav** [comment]
Both queries failed with:
```
java.lang.AssertionError: Expected <1> column of type <LONGNVARCHAR>, but was <CHAR>, actual columns: [DECIMAL, CHAR, CHAR, INTEGER, BIGINT]
```
The second column of both queries is a projection of `i_category`, which comes from the `item` table and in the specification has a `char(50)` datatype. Therefore I think switching from `LONGNVARCHAR` to `CHAR` is fine.

Not sure why this mismatch is only appearing now.

cc @losipiuk @kokosing @cawallin @rschlussel

**Review by cawallin — APPROVED** [review]
Maybe since GROUPING support was last added to the sprint branch, we changed the datatypes here. This looks good -- but if you generated results from the new query by dumping Presto's results, please double check against postgres (from a rough glance it looks fine)

**Review by rschlussel-zz — APPROVED** [review]

**Comment by petroav** [comment]
I didn't check these results against anything but I think that's OK because the Github diff shows that no actual data changed and the only material edit is the addition of space characters.

I'll wait to merge this until either @losipiuk or @kokosing chime in to give some perspective on why these data types weren't updated earlier just to make sure I'm not violating some implicit requirement/dependency. If you think the change is good you can merge it during your AM and don't have to wait for me to do it.

**Comment by kokosing** [comment]
There was a mistake some time ago in TPCDS schema, which was fixed in tempto 1.24. Unfortunately, these tests were not updated up to it. I think it could due the fact that they were quarantined for a long time.

I am going to merge this to release branch. 

I think this change should go together with `GROPING` support PR as I think it should be merged together into master someday ;)

**Pull request merged**
